### ISSUE TITLE
Frontend todo

### ISSUE THREAD

**Issue by geraltofrivia** [AskNowQA/QA-Tutorial#1]
- [ ] Standardize padding across the file b/w (divider and sectionheader)
- [ ] Add footer
- [ ] Add requirements @ a glance
- [ ] Add mendeley group and manual citation download link 
- [ ] Every link needs to open in new tab
- [ ] Add link to ESWC
